### PR TITLE
Adds RISC-V 32bit platform support

### PR DESCRIPTION
**Pull request by denizzzka**
Current state: compiles, but not works on real hardware due to few non-implemented code stubs

### CODE REVIEW

**Comment by kassane** [comment]
@denizzzka missing add `+zicsr` & `+zifencei`

### References
- https://discourse.llvm.org/t/support-for-zicsr-and-zifencei-extensions/68369
- https://github.com/espressif/esp-idf/blob/master/tools/cmake/toolchain-esp32c3.cmake
- https://github.com/esp-rs/esp-idf-sys/issues/176

**Comment by denizzzka** [comment]
@kassane Thank you!
Fixed in https://github.com/denizzzka/dfruntime/commit/8f8d068681d75098cdbcac8ab568f4ae8e0be6aa

**Comment by denizzzka** [comment]
@kassane If you are interested in RISC-V currently I actively develope branch https://github.com/denizzzka/d_c_arm_test/tree/add_esp-idf - all latest changes are only there

**Comment by kassane** [comment]
@denizzzka my patch for
https://github.com/denizzzka/d_c_arm_test/blob/3c8a7eeca9b7bd13d855b3412ce23a19853f2431/ESP-IDF_demo_project/main/CMakeLists.txt#L1-L4

```diff
diff --git a/ESP-IDF_demo_project/main/CMakeLists.txt b/ESP-IDF_demo_project/main/CMakeLists.txt
index 362a277..bdcec6c 100644
--- a/ESP-IDF_demo_project/main/CMakeLists.txt
+++ b/ESP-IDF_demo_project/main/CMakeLists.txt
@@ -1,6 +1,26 @@
-if(NOT (${IDF_TARGET} STREQUAL "esp32c3"))
-     #FIXME:
-     message(FATAL_ERROR "Only esp32c3 target is supported")
+idf_build_get_property(target IDF_TARGET)
+idf_build_get_property(arch IDF_TARGET_ARCH)
+
+# llvm-upstream not have support yet for xtensa (espressif cpus)
+if("${arch}" STREQUAL "xtensa")
+     message(FATAL_ERROR "Not supported target: ${target}")
+else()
+     set(triple_target "riscv32-unknown-newlib-elf")
+endif()
+
+if(${target} STREQUAL "esp32c2" OR ${target} STREQUAL "esp32c3")
+     set(march_flag "rv32imc_zicsr_zifencei")
+     set(mattr_flag "+m,+c,+zicsr,+zifencei")
+     set(mabi_flag "ilp32")
+elseif(${target} STREQUAL "esp32p4")
+     set(march_flag "rv32imafc_zicsr_zifencei")
+     # optional +xesppie (espressif vendor extensions) - llvm-upstream no support yet
+     set(mattr_flag "+a,+m,+c,+f,+zicsr,+zifencei")
+     set(mabi_flag "ilp32f")
+else()
+     set(march_flag "rv32imac_zicsr_zifencei")
+     set(mattr_flag "+a,+m,+c,+zicsr,+zifencei")
+     set(mabi_flag "ilp32")
 endif()
 
 if(DEFINED ENV{PRESERVE_I_FILES})
@@ -24,25 +44,38 @@ set(D_COMPILER_FLAGS
 )
 
 if(CMAKE_BUILD_TYPE STREQUAL "Debug")
-    list(APPEND D_COMPILER_FLAGS "-g")
+     list(APPEND D_COMPILER_FLAGS "-g")
 endif()
 
-set(D_OBJ_PATH "${CMAKE_BINARY_DIR}/d_obj.o")
+list(APPEND D_COMPILER_FLAGS "-mtriple=${triple_target}")
+list(APPEND D_COMPILER_FLAGS "-mattr=${mattr_flag}")
+list(APPEND D_COMPILER_FLAGS "-mabi=${mabi_flag}")
 
-add_custom_command(
-     OUTPUT ${D_OBJ_PATH}
-     COMMAND ${D_COMPILER} ${D_COMPILER_FLAGS} -c "-of=${D_OBJ_PATH}"
-     "${CMAKE_SOURCE_DIR}/main/main.d"
-     "${CMAKE_SOURCE_DIR}/main/esp_idf_binding.d"
-)
+# USE Cimport
+# list(APPEND D_COMPILER_FLAGS "-P-march ${march_flag}")
+
+# lib filepath
+set(D_OBJ_PATH "${CMAKE_BINARY_DIR}/lib/libd.a")
+
+
+add_custom_target(
+     d_build
+     ${D_COMPILER}
+     ${D_COMPILER_FLAGS}
+     -lib "-of=${D_OBJ_PATH}"
+     ${CMAKE_SOURCE_DIR}/main/main.d
+     ${CMAKE_SOURCE_DIR}/main/esp_idf_binding.d # need druntime/stdc
+     WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
+     BYPRODUCTS ${CMAKE_BINARY_DIR}/lib/libd.a
+     VERBATIM)
 
+add_prebuilt_library(d ${CMAKE_BINARY_DIR}/lib/libd.a)
 if(NOT DEFINED ENV{PRESERVE_I_FILES})
-     add_library(d_obj STATIC ${D_OBJ_PATH})
-     set_target_properties(d_obj PROPERTIES LINKER_LANGUAGE C)
-     target_link_libraries(${COMPONENT_LIB} d_obj)
+     add_dependencies(d d_build)
+     target_link_libraries(${COMPONENT_LIB} PRIVATE ${CMAKE_BINARY_DIR}/lib/libd.a)
 
      #TODO: remove
-     set(DSTDLIBS "/home/denizzz/Dev/dfruntime/install_freertos_riscv32/lib")
-     target_link_libraries(${COMPONENT_LIB} ${DSTDLIBS}/libdruntime-ldc-debug.a)
-     target_link_libraries(${COMPONENT_LIB} ${DSTDLIBS}/libphobos2-ldc-debug.a)
+     # set(DSTDLIBS "/home/denizzz/Dev/dfruntime/install_freertos_riscv32/lib")
+     # target_link_libraries(${COMPONENT_LIB} ${DSTDLIBS}/libdruntime-ldc-debug.a)
+     # target_link_libraries(${COMPONENT_LIB} ${DSTDLIBS}/libphobos2-ldc-debug.a)
 endif()
```

**Pull request merged**
